version: '3.6'

services:
  frontend:
    image: pawnshop/frontend-prod:latest
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "3000:3000"
    env_file: .env.production

volumes:
  postgres_data:
