version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  lint:
    machine: true
    steps:
      - checkout
      - node/install-packages:
          override-ci-command: npm install
      - run:
          name:
          command: |
            npm run lint

  deploy-dev:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and Deploy to Vercel dev
          command: |
            set -x
            npm install --global vercel@latest
            export VERCEL_PROJECT_ID=${VERCEL_PROJECT_ID_DEV}
            vercel pull --yes --environment=preview --token=${VERCEL_TOKEN}
            vercel build --prod --token=${VERCEL_TOKEN}
            vercel deploy --prebuilt --prod --token=${VERCEL_TOKEN}

  deploy-main:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and Deploy to Vercel prod
          command: |
            set -x
            npm install --global vercel@latest
            export VERCEL_PROJECT_ID=${VERCEL_PROJECT_ID_MAIN}
            vercel pull --yes --environment=production --token=${VERCEL_TOKEN}
            vercel build --prod --token=${VERCEL_TOKEN}
            vercel deploy --prebuilt --prod --token=${VERCEL_TOKEN}

workflows:
  lint-deploy:
    jobs:
      - lint
      - deploy-dev:
          requires:
            - lint
          filters:
            branches:
              only:
                - dev
      - deploy-main:
          requires:
            - lint
          filters:
            branches:
              only:
                - main
