version: 2.1

orbs:
  node: circleci/node@5.0.2

executors:
  my-executor:
    docker:
      - image: zlapik/pawnshop-backend_backend

jobs:
  lint:
    machine: true
    steps:
      - checkout
      - node/install-packages:
          override-ci-command: npm install
      - run:
          name:
          command: |
            sudo pip3 install pre-commit
            pre-commit run --all-files

  deploy-dev:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and Deploy to Vercel DEV
          command: |
            set -x
            npm install --global vercel@latest
            export VERCEL_PROJECT_ID=${VERCEL_PROJECT_ID_DEV}
            vercel pull --yes --environment=preview --token=${VERCEL_TOKEN}
            vercel build --token=${VERCEL_TOKEN}
            vercel deploy --prebuilt --token=${VERCEL_TOKEN}

  deploy-main:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and Deploy to Vercel PROD
          command: |
            set -x
            npm install --global vercel@latest
            export VERCEL_PROJECT_ID=${VERCEL_PROJECT_ID_MAIN}
            vercel pull --yes --environment=production --token=${VERCEL_TOKEN}
            vercel build --prod --token=${VERCEL_TOKEN}
            vercel deploy --prebuilt --prod --token=${VERCEL_TOKEN}

workflows:
  deploy:
    jobs:
      - lint
      - deploy-dev:
          requires:
            - lint
          filters:
            branches:
              only:
                - dev
      - deploy-main:
          requires:
            - lint
          filters:
            branches:
              only:
                - main
