import type { NextPage } from 'next'
import Head from 'next/head'
import { MainLayout } from '@components/big/MainLayout'

const Bazar: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Bazar</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <MainLayout>
        <div>Bazar</div>
      </MainLayout>
    </div>
  )
}

export default Bazar
