import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">INDEX PAGE</h1>
        <h1 className="text-3xl font-bold underline">INDEX PAGE2 test fro circleci</h1>
      </main>
    </div>
  )
}

export default Home
