import type { NextPage } from 'next'
import Head from 'next/head'

const Login: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="flex h-screen items-center justify-center bg-gray-200">
        <h1 className="">LOGIN</h1>
      </main>
    </div>
  )
}

export default Login
