import type { NextPage } from 'next'
import Head from 'next/head'
import { MainLayout } from '@components/big/MainLayout'

const Medzisklad: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Medzisklad</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <MainLayout>
          <div>Medzisklad</div>
        </MainLayout>
      </main>
    </div>
  )
}

export default Medzisklad
