import type { NextPage } from 'next'
import Head from 'next/head'
import { MainLayout } from '@components/big/MainLayout'

const Zastavarna: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Zastavarna</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <MainLayout>
          <div>Zastavarna</div>
        </MainLayout>
      </main>
    </div>
  )
}

export default Zastavarna
